### PR TITLE
Override config name to use by passing setting NSCONF in env

### PR DESCRIPTION
**Pull request by jacobsvante**
Useful when working with multiple environments.

### CODE REVIEW

**Comment by danieljoppi** [comment]
Can you update the README.md? And include the new configuration?

**Comment by jacobsvante** [comment]
Done.

**Comment by jacobsvante** [comment]
Awesome. Could you release a new npm version of `nsconfig` and `nscabinet` (with this feature)? 😀

**Comment by danieljoppi** [comment]
published ... [nsconfig@0.5.0](https://www.npmjs.com/package/nsconfig)

**Comment by wkrueger** [comment]
Good one! Suggesting a change, though!
https://github.com/suiteplus/nsconfig/pull/8/files

**Comment by jacobsvante** [comment]
Thanks! That means I will be anxiously waiting for [this related nscabinet issue](https://github.com/suiteplus/nscabinet/issues/18) to be solved now 😉

**Pull request merged**
